//
//  RAAlertManager.h
//  RAAlerts
//
//  Created by Joshua Buhler on 2/21/13.
//  Copyright (c) 2013 Rain.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to
//  deal in the Software without restriction, including without limitation the
//  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
//  IN THE SOFTWARE.
//

#import <Foundation/Foundation.h>

#import "RAAlertView.h"

@interface RAAlertManager : NSObject

//  The time interval used to combine alerts of the same type. Any alerts with
//  the same title will be combined if displayed during the time between the
//  first instance of the alert and the time interval defined by combineWindow.
@property (nonatomic, assign) NSTimeInterval combineWindow;

//  Returns the default instance of RAAlertManager. Multiple managers may be used
//  if needed.
+ (RAAlertManager *) defaultManager;

//  Displays the specified alert. Alerts presented through this method will be
//  delayed by the value specified by combineWindow. Best used with alerts that
//  may be generated by automated processes and not by user-initiated events.
//  You wouldn't want a one second delay between a user tapping a button and
//  when an alert is displayed.
- (void) showAlert:(RAAlertView *)alert;

@end
